config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing'

  devise_for :users,
    path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index, :show, :update, :destroy]

  resources :albums do
    resources :comments, only: [:create, :update, :destroy]
    collection do
      get 'search'
      get 'stats(/:year)', to: 'albums#stats', as: 'stats'
    end
  end

  resources :lists do
    member do
      patch 'albums/:album_id', to: 'lists#move_album', as: 'move_album'
      delete 'albums/:album_id', to: 'lists#delete_album', as: 'delete_album'
    end
  end

  scope :api do
    get 'artists', to: 'albums#artists'
    get 'labels', to: 'albums#labels'
    post 'rate/:album_id', to: 'rates#create', as: 'rate'
  end

  get 'robots.:format', to: 'pages#robots'
  get 'sitemap.xml.gz', to: 'pages#sitemap'
  get 'status', to: 'pages#status'
end

app/models/list.rb
class List
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  extend Enumerize

  belongs_to :user
  has_and_belongs_to_many :albums

  field :category
  enumerize :category, in: [:personal, :community, :staff], default: :personal, predicates: true

  field :title,     type: String
  field :positions, type: Array,   default: []
  field :closed,    type: Boolean, default: false

  validates :title,    presence: true
  validates :category, presence: true
  validates :user,     presence: true

  slug :title

  scope :opened, -> { where(closed: false) }

  scope :personal, -> { where(category: :personal) }
  scope :community, -> { where(category: :community) }
  scope :staff, -> { where(category: :staff) }

  def move_album(album, direction)
    return unless albums.include?(album)

    left = albums.asc.to_a.index(album)
    index = positions[left]

    if direction == :up
      return unless index > 1
      right = positions.index(index - 1)
    elsif direction == :down
      return unless index < positions.size
      right = positions.index(index + 1)
    end

    positions[left], positions[right] = positions[right], positions[left]
  end

  def delete_album(album)
    return unless albums.include?(album)

    index = positions[albums.asc.to_a.index(album)]
    positions.delete(index)
    albums.delete(album)

    positions.map! do |p|
      if p > index
        p - 1
      elsif p < index
        p
      end
    end
  end

  def ranked_albums
    positioned_albums = positions.zip(albums.asc)
    positioned_albums.sort.transpose.last
  end

  def self.categories_for_select
    category.values.map do |category|
      [
        category.to_s.titleize,
        category
      ]
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.includes(:user, :albums).all
    authorize List
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    authorize @list
  end

  # GET /lists/new
  def new
    @list = List.new
    authorize @list
  end

  # GET /lists/1/edit
  def edit
    authorize @list
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    authorize @list
    @list.user = current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    authorize @list
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    authorize @list
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  def move_album
    list = List.find(params[:id])
    authorize list
    album = Album.find(params[:album_id])
    list.move_album(album, params[:direction].to_sym)
    list.save!
    redirect_to list, turbolinks: true
  end

  def delete_album
    list = List.find(params[:id])
    authorize list
    album = Album.find(params[:album_id])
    list.delete_album(album)
    list.save!
    redirect_to list, turbolinks: true
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title, :category, :closed)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.haml
= simple_form_for @list do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :category, as: :radio_buttons
    - if action_name == 'edit'
      = f.input :closed, as: :radio_buttons 

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/lists/_list.html.haml
%li.media
  .media-left
    - if list.albums.present?
      = image_tag list.ranked_albums.first.artwork, class: 'media-object', size: '50', alt: list.title
    - else
      = image_tag list.user.gravatar_url, class: 'media-object', size: '50', alt: list.title
  .media-body
    %h4.media-heading
      = link_to list.title, list
    .text-muted
      = "by #{list.user.username}"

app/views/lists/_ranked_album.html.haml
.row.ranked-album
  .col-md-1.col-md-offset-1
    .rank
      .rank-number= ranked_album_counter + 1
      - if policy(list).update? && !list.closed
        .rank-direction-buttons
          = form_tag move_album_list_path(list, ranked_album), method: :patch do
            = hidden_field_tag :direction, :up
            = button_tag type: 'submit', class: 'btn btn-lg' do
              %i.glyphicon.glyphicon-chevron-up
          = form_tag move_album_list_path(list, ranked_album), method: :patch do
            = hidden_field_tag :direction, :down
            = button_tag type: 'submit', class: 'btn btn-lg' do
              %i.glyphicon.glyphicon-chevron-down
        .rank-delete-button
          = link_to delete_album_list_path(list, ranked_album), method: :delete, data: { confirm: 'Are you sure?' } do
            %i.glyphicon.glyphicon-remove

  .col-md-9
    = render partial: 'shared/card', object: ranked_album

app/views/lists/edit.html.haml
%h2 Editing List

= render 'form'

app/views/lists/index.html.haml
- title 'Lists'

.album-lists
  .col-sm-4
    %h3 Personal Lists
    %ul.media-list
      = render partial: 'list', collection: @lists.personal
    = link_to 'Create List', new_list_path, class: 'btn btn-primary'
  .col-sm-4
    %h3 Community Lists
    %ul.media-list
      = render partial: 'list', collection: @lists.community
  .col-sm-4
    %h3 Staff Lists
    %ul.media-list
      = render partial: 'list', collection: @lists.staff

app/views/lists/new.html.haml
%h2 New List

= render 'form'

app/views/lists/show.html.haml
- title @list.title

.col-md-10.col-md-offset-1
  %h2.text-center.list-title
    = @list.title
    %span.text-muted= "by #{@list.user.username}"
    - if policy(@list).update?
      = link_to edit_list_path @list do
        %span.glyphicon.glyphicon-pencil
      = link_to @list, method: :delete, data: { confirm: 'Are you sure?' } do
        %span.glyphicon.glyphicon-remove

.col-md-12
  = render partial: 'ranked_album', locals: { list: @list }, collection: @list.ranked_albums