config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing'

  devise_for :users,
    path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index, :show, :update, :destroy]

  resources :albums do
    resources :comments, only: [:create, :update, :destroy]
    collection do
      get 'search'
      get 'stats(/:year)', to: 'albums#stats', as: 'stats'
    end
  end

  resources :lists do
    member do
      patch 'albums/:album_id', to: 'lists#move_album', as: 'move_album'
      delete 'albums/:album_id', to: 'lists#delete_album', as: 'delete_album'
    end
  end

  scope :api do
    get 'artists', to: 'albums#artists'
    get 'labels', to: 'albums#labels'
    post 'rate/:album_id', to: 'rates#create', as: 'rate'
  end

  get 'robots.:format', to: 'pages#robots'
  get 'sitemap.xml.gz', to: 'pages#sitemap'
  get 'status', to: 'pages#status'
end

app/views/shared/_card.html.haml
- cache card do
  .well.well-sm.card{ 'data-album-id' => card.id }
    .row
      .col-lg-4
        = link_to album_path(card) do
          = image_tag card.artwork, alt: card.title, class: %w(artwork img-thumbnail img-responsive)
      .col-lg-5
        %h3= link_to card.title, album_path(card)
        %h4= raw card.artist.map { |artist| link_to artist, albums_path(artist: artist) }.join(' / ')
        %h5= link_to card.year, albums_path(year: card.year)
        %h5= card.genre.join(' • ')
        %h5= raw card.label.map { |label| link_to label, albums_path(label: label) }.join(' / ')
        %h6= card.date.strftime('%d %b %Y')
        %h6= link_to 'Read review at Pitchfork', card.source
      .col-lg-3
        - if card.bnm
          .rating.bnm= card.rating
        - elsif card.reissue
          .rating.reissue= card.rating
        - else
          .rating= card.rating

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default.navbar-inverse.navbar-static-top
  .container
    .navbar-header
      = button_tag type: 'button', class: ['navbar-toggle', 'collapsed'], data: { toggle: 'collapse', target: '#navbar-collapse-button' } do
        %span.sr-only<
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'A', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse#navbar-collapse-button
      %ul.nav.navbar-nav.navbar-left
        %li= link_to 'Albums', albums_path
        %li.dropdown
          = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }, role: 'button' do
            = precede 'Top Albums' do
              %span.caret
          %ul.dropdown-menu{ role: 'menu' }
            - 6.years.ago.year.upto Time.now.year do |year|
              %li= link_to year, albums_path(year: year, order: :rating, dir: :desc, reissue: 0)
        - if user_signed_in?
          - if current_user.try(:admin?)
            %li= link_to 'Search', search_albums_path
        %li= link_to 'Lists', lists_path
        %li= link_to 'Stats', stats_albums_path(Time.now.year)
        %li= link_to 'Users', users_path
        %li= link_to 'Status', status_path

      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= image_tag current_user.gravatar_url, size: '65', alt: current_user.username
          %li= link_to 'Edit Profile', edit_user_registration_path
          %li= link_to 'Log Out', destroy_user_session_path, method: 'delete'
        - else
          %li= link_to 'Log In', new_user_session_path
          %li= link_to 'Sign Up', new_user_registration_path

      %ul.navbar-form.navbar-right
        = form_tag search_albums_path, method: 'get' do
          = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search'