config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing'

  devise_for :users,
    path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index, :show, :update, :destroy]

  resources :albums do
    resources :comments, only: [:create, :update, :destroy]
    collection do
      get 'search'
      get 'stats(/:year)', to: 'albums#stats', as: 'stats'
    end
  end

  resources :lists do
    member do
      patch 'albums/:album_id', to: 'lists#move_album', as: 'move_album'
      delete 'albums/:album_id', to: 'lists#delete_album', as: 'delete_album'
    end
  end

  scope :api do
    get 'artists', to: 'albums#artists'
    get 'labels', to: 'albums#labels'
    post 'rate/:album_id', to: 'rates#create', as: 'rate'
  end

  get 'robots.:format', to: 'pages#robots'
  get 'sitemap.xml.gz', to: 'pages#sitemap'
  get 'status', to: 'pages#status'
end

app/models/album.rb
class Album
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  field :title, type: String
  field :p4k_id, type: Integer
  field :artist, type: Array
  field :label, type: Array
  field :year, type: String
  field :date, type: Date
  field :artwork, type: String
  field :source, type: String
  field :genre, type: Array
  field :reviewer, type: String
  field :rating, type: Float
  field :reissue, type: Boolean
  field :bnm, type: Boolean

  validates :title, presence: true
  validates :p4k_id, uniqueness: true
  validates :artist, presence: true
  validates :label, presence: true
  validates :year, presence: true
  validates :date, presence: true
  validates :artwork, presence: true
  validates :source, presence: true, uniqueness: true
  validates :reviewer, presence: true
  validates :rating, presence: true, numericality: true
  validates :reissue, presence: true
  validates :bnm, presence: true

  index(title: 1)
  index(artist: 1)
  index(label: 1)
  index(rating: 1)
  index(date: -1, created_at: 1)
  index({ source: 1 }, unique: true)
  # An index that is both sparse and unique prevents collection
  # from having documents with duplicate values for a field
  # but allows multiple documents without the key.
  index({ p4k_id: 1 }, unique: true, sparse: true)

  has_and_belongs_to_many :lists, before_add: :set_position
  has_many :rates, dependent: :destroy
  embeds_many :comments # implies dependent: :destroy

  slug :artist, :title

  scope :artist, -> (artist) { where(artist: artist) if artist.present? }
  scope :year, -> (year) { where(year: year) if year.present? }
  scope :genre, -> (genre) { where(genre: genre) if genre.present? }
  scope :label, -> (label) { where(label: label) if label.present? }
  scope :reissue, -> (reissue) { reissue == '0' ? where(reissue: false) : where(reissue: true) if reissue.present? }
  scope :bnm, -> (bnm) { bnm == '0' ? where(bnm: false) : where(bnm: true) if bnm.present? }
  scope :rating_range, -> (min, max) { gte(rating: min).lte(rating: max) }
  scope :albums_order, -> (order, dir) { order_by(order => dir, created_at: :asc) }

  def self.search(query)
    if query.present?
      re = ::Regexp.new(query, true)
      any_of([
        { artist: re },
        { title: re },
        { label: re }
      ])
    else
      all
    end
  end

  private

  def set_position(list)
    return if lists.include? list
    list.positions << list.positions.size + 1
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    params[:order]  ||= 'date'
    params[:dir]    ||= 'desc'
    params[:rating] ||= '0.0-10.0'

    rating = params[:rating].split('-')
    min_rating = rating[0]
    max_rating = rating[1]

    @albums = Album.artist(params[:artist])
                   .year(params[:year])
                   .genre(params[:genre])
                   .label(params[:label])
                   .reissue(params[:reissue])
                   .bnm(params[:bnm])
                   .rating_range(min_rating, max_rating)
                   .albums_order(params[:order], params[:dir])
                   .search(params[:search])
                   .page(params[:page])

    @albums_page_count = Rails.cache.fetch ['albums_count', params.permit!], expires_in: 2.hours do
      (@albums.count / Kaminari.config.default_per_page.to_f).ceil
    end
  end

  # GET /api/artists.json
  def artists
    @artists = Rails.cache.fetch 'artists', expires_in: 2.hours do
      Album.distinct('artist').sort
    end
  end

  # GET /api/labels.json
  def labels
    @labels = Rails.cache.fetch 'labels', expires_in: 2.hours do
      Album.distinct('label').sort
    end
  end

  # GET /albums/search
  def search
    albums = Album.search(params[:search])
    albums = albums.desc(:updated_at) if params[:lastupdated]
    @albums = albums.page(params[:page])
    authorize @albums
  end

  # GET /albums/stats
  # GET /albums/stats.json
  def stats
    pipeline = []
    pipeline << {
      '$match' => {
        'date' => {
          '$gte' => Date.new(params[:year].to_i, 1, 1),
          '$lte' => Date.new(params[:year].to_i, 12, 31)
        }
      }
    } if params[:year]
    pipeline << {
      '$group' => {
        '_id' => '$date',
        'avg_rating' => { '$avg' => '$rating' }
      }
    }
    pipeline << { '$sort' => { '_id' => 1 } }

    stats = Album.collection.aggregate(pipeline)

    @total = {
      album: Album.year(params[:year]).count,
      bnm: Album.year(params[:year]).where(bnm: true).count,
      reissue: Album.year(params[:year]).where(reissue: true).count,
      discogs: Album.year(params[:year]).not.where(discogs: nil).count
    }

    respond_to do |format|
      format.html { render :stats }
      format.json { render json: stats }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @comments = @album.comments.all

    return unless user_signed_in?
    @comment = @album.comments.build

    if @album.rates.where(user_id: current_user.id).exists?
      @rate = @album.rates.find_by(user_id: current_user.id)
    end

    return unless @current_user.lists.opened.present?
    @lists = @current_user.lists.opened - @album.lists
  end

  # GET /albums/new
  def new
    @album = Album.new
    authorize @album
  end

  # GET /albums/1/edit
  def edit
    authorize @album
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    authorize @album

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    if album_params[:list_id]
      list = List.find(album_params[:list_id])
      @album.lists.push(list)
      redirect_to list, notice: 'Album was successfully added to this List'
    else
      authorize @album
      respond_to do |format|
        if @album.update(album_params)
          format.html { redirect_to @album, notice: 'Album was successfully updated' }
          format.json { render :show, status: :ok, location: @album }
        else
          format.html { render :edit }
          format.json { render json: @album.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    authorize @album
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:title, :p4k_id, :year, :artwork, :source, :list_id,
      :date, :reviewer, :rating, :reissue, :bnm, artist: [], label: [], genre: [])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def toggle_button(name, value)
    active = true if params[name] == value

    content_tag :div, class: "btn btn-primary #{name} #{'active' if active}" do
      concat content_tag :input, nil, type: 'radio', name: name, id: "#{name}_#{value}", value: value, checked: active
      concat content_tag :span, nil, class: "glyphicon glyphicon-sort-by-attributes#{'-alt' if value == 'asc'}"
    end
  end
end

app/views/albums/_dash.html.haml
= form_tag albums_path, method: :get, id: 'filter' do
  = label_tag :album
  .form-group
    = text_field_tag :artist, params[:artist], class: 'form-control', id: 'artists-typeahead', placeholder: 'Artist', autocomplete: 'off'
  .form-group
    = text_field_tag :year, params[:year], class: 'form-control', placeholder: 'Year', autocomplete: 'off'
  .form-group
    = select_tag 'genre', options_for_select(%w(Rock Electronic Rap Pop/R&B Experimental Jazz Global Metal Folk/Country), params[:genre]), class: 'form-control', prompt: 'Genre'
  .form-group
    = text_field_tag :label, params[:label], class: 'form-control', id: 'labels-typeahead', placeholder: 'Label', autocomplete: 'off'
  .form-group
    = label_tag :rating
    = text_field_tag :rating, nil, hidden: true
  .form-group
    = label_tag :order
    .input-group
      = select_tag 'order', options_for_select([['Review Date', :date],
                                                ['Rating', :rating],
                                                ['Year of Release', :year],
                                                ['Artist', :artist],
                                                ['Label', :label]],
                                                params[:order]),
                                                class: 'form-control'
      .input-group-btn
        .toggler{ data: { toggle: 'buttons' } }
          = toggle_button(:dir, 'desc')
          = toggle_button(:dir, 'asc')
  .form-group
    %label.btn.btn-danger#bnm-btn
      - if params[:bnm].present?
        - if params[:bnm] == '0'
          = hidden_field_tag :bnm, 0
          %span<
            No Best New Music
        - else
          = hidden_field_tag :bnm, 1
          %span<
            Only Best New Music
      - else
        = hidden_field_tag :bnm, nil
        %span<
          Include Best New Music
  .form-group
    %label.btn.btn-success#reissue-btn
      - if params[:reissue].present?
        - if params[:reissue] == '0'
          = hidden_field_tag :reissue, 0
          %span<
            No Reissues
        - else
          = hidden_field_tag :reissue, 1
          %span<
            Only Reissues
      - else
        = hidden_field_tag :reissue, nil
        %span<
          Include Reissues
  %button.btn.btn-default.btn-block= 'Search'

app/views/albums/_form.html.haml
= simple_form_for @album do |f|
  = f.error_notification

  = f.input :title
  = f.input :artist, input_html: { multiple: true }
  = f.input :label, input_html: { multiple: true }
  = f.input :year
  = f.input :genre, input_html: { multiple: true }
  = f.input :date
  = f.input :artwork
  = f.input :reviewer
  = f.input :source
  = f.input :rating
  = f.input :reissue, as: :boolean
  = f.input :bnm, as: :boolean
  = f.button :submit, class: 'btn-primary'

app/views/albums/edit.html.haml
- title "Editing #{@album.title}"

.col-md-offset-2.col-md-8
  %h2= 'Editing Album'

  = render 'form'

  = link_to 'Show', @album
  = link_to 'Back', albums_path

app/views/albums/index.html.haml
- title params[:artist] ? params[:artist] : 'Albums'

.col-lg-3.col-md-4
  .well.well-sm#dash
    = render 'dash'

.col-lg-9.col-md-8
  - if @albums.empty?
    %h5.text-muted Nothing Found
  - else
    = render partial: 'shared/card', collection: @albums
    = paginate @albums, total_pages: @albums_page_count

app/views/albums/new.html.haml
%h1= 'New Album'

= render 'form'

= link_to 'Back', albums_path

app/views/albums/search.html.haml
- title 'Search Albums'

.col-xs-12

  %h3= 'Search Albums'

  .row
    .col-md-2
      - if params[:lastupdated]
        = link_to 'Show Last Added', search_albums_path, class: 'btn btn-info'
      - else
        = link_to 'Show Last Updated', search_albums_path(lastupdated: true), class: 'btn btn-info'
    .col-md-8
      = form_tag search_albums_path, method: 'get', class: 'input-group' do
        = text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search'
        %span.input-group-btn= submit_tag 'Search', name: nil, class: 'btn btn-primary'

  %br

  .table-responsive
    %table.table.table-striped.table-bordered.table-condensed.table-hover
      %thead
        %tr
          %th= 'Artwork'
          %th= 'Title'
          %th= 'Artist'
          %th= 'Label'
          %th= 'Genre'
          %th= 'Year'
          %th= 'Published'
          %th= 'Created'
          %th= 'Updated'
          %th= 'Source'
          %th= 'Rating'
          %th= 'Reissue'
          %th= 'Bnm'
          %th{ colspan: '3' }= 'Actions'

      %tbody.text-center
        - @albums.each do |album|
          %tr
            %td= image_tag album.artwork, size: '100'
            %td= link_to album.title, album_path(album)
            %td= album.artist.join(' / ')
            %td= album.label.join(' / ')
            %td= album.genre.join(' • ')
            %td= album.year
            %td.text-nowrap= album.date
            %td.text-nowrap= album.created_at.strftime('%d.%m.%Y %H:%M')
            %td.text-nowrap= album.updated_at.strftime('%d.%m.%Y %H:%M')
            %td= link_to 'Pitchfork Link', album.source
            %td= album.rating
            %td= album.reissue
            %td= album.bnm
            %td= link_to 'Show', album
            %td= link_to 'Edit', edit_album_path(album)
            %td= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' }

  = paginate @albums

  %br

  = link_to 'New Album', new_album_path

app/views/albums/show.html.haml
- title "#{@album.artist.join(' / ')} - #{@album.title}"

.col-xs-12
  .well.well-sm
    .row.card{ 'data-album-id' => @album.id }
      .col-lg-3.col-md-4.col-sm-6.col-xs-12
        = image_tag @album.artwork, alt: @album.title, class: 'artwork img-thumbnail img-responsive'
      .col-lg-5.col-md-4.col-sm-6.col-xs-12
        %h3= link_to @album.title, album_path(@album)
        %h4= raw @album.artist.map { |artist| link_to artist, albums_path(artist: artist) }.join(' / ')
        %h5= link_to @album.year, albums_path(year: @album.year)
        %h5= @album.genre.join(' • ')
        %h5= raw @album.label.map { |label| link_to label, albums_path(label: label) }.join(' / ')
        %h6= @album.date.strftime('%d %b %Y')
        %h6= link_to 'Read review at Pitchfork', @album.source
        - if @lists.present?
          = form_tag @album, method: :patch do
            = select_tag('album[list_id]', options_from_collection_for_select(@lists, :id, :title))
            = submit_tag('Add to List', class: 'btn btn-xs btn-primary')
      .col-lg-2.col-md-4.col-sm-6.hidden-xs
        - if user_signed_in?
          - if @rate
            .rating.user= @rate.rate
          - else
            .rating.user.dim= 0.0
      .col-lg-2.col-md-4.col-sm-6.col-xs-12
        - if @album.bnm
          .rating.bnm= @album.rating
        - elsif @album.reissue
          .rating.reissue= @album.rating
        - else
          .rating= @album.rating

    - if @album[:discogs]
      .row
        - if @album[:discogs][:tracklist]
          .col-lg-12
            .panel.panel-success.discogs
              .panel-heading
                Discogs data
                %span.pull-right.collapse-arrow
                  %i.glyphicon.glyphicon-chevron-up
              .panel-body
                %h4.tracklist
                  Tracklist:
                %ol
                  - @album[:discogs][:tracklist].each do |track|
                    %li= track[:title]

        - if @album[:discogs][:videos]
          .col-lg-12
            .panel.panel-info.discogs
              .panel-heading.panel-collapsed
                Videos
                %span.pull-right.collapse-arrow
                  %i.glyphicon.glyphicon-chevron-down
              .panel-body{ style: 'display: none' }
                - @album[:discogs][:videos].take(3).each do |video|
                  .col-lg-4
                    .embed-responsive.embed-responsive-16by9
                      %iframe.embed-responsive-item.lazyload{ 'data-src' => video[:uri].sub('watch?v=', 'embed/') }

  - if user_signed_in?
    - if current_user.try(:admin?)
      = link_to 'Edit', edit_album_path(@album)
      = link_to 'Destroy', @album, method: :delete, data: { confirm: 'Are you sure?' }
  = link_to 'Back', :back

  %h3 Comments
  - if @comments.blank?
    %h5.text-muted The comments section is empty
  - else
    - @comments.each do |comment|
      .well.well-sm
        = image_tag comment.user_avatar, size: '33'
        %strong= comment.user_name
        = comment.body

  - if user_signed_in?
    = render 'comments/form'

app/views/albums/stats.html.haml
- title 'Stats'

.col-xs-12
  .row
    .col-xs-12
      %h2
        %p.pull-left
          != 'Stats&nbsp;'
        .dropdown
          = button_tag class: 'btn btn-default dropdown-toggle', data: { toggle: 'dropdown' } do
            = params[:year] ||= 'overall'
            %span.caret
          %ul.dropdown-menu
            %li= link_to 'overall', stats_albums_path
            - Time.now.year.downto 1999 do |year|
              %li= link_to year, stats_albums_path(year)

      #chartid{ style: 'width: 100%; height: 400px; background-color: #282828;' }

  %br

  .row
    .col-md-3
      .panel.panel-default
        .panel-body
          .text-center
            %strong
              Total albums:
            = @total[:album]
    .col-md-3
      .panel.panel-default
        .panel-body
          .text-center
            %strong
              Total BNMs:
            = @total[:bnm]
    .col-md-3
      .panel.panel-default
        .panel-body
          .text-center
            %strong
              Total reissues:
            = @total[:reissue]
    .col-md-3
      .panel.panel-default
        .panel-body
          .text-center
            %strong
              Discogs data:
            = @total[:discogs]